import {
  BarChart2,
  LayoutDashboard,
  FileUp,
  ShoppingBag,
  MessageSquare,
  Bot,
  CheckCircle2,
  Clock,
  Users,
  Info,
  ArrowLeft,
  MessageCircle,
  ArrowRight,
  FileArchive,
  X,
  UploadCloud,
  XCircle,
  AlertTriangle,
} from "lucide-react";

export const Icons = {
  analytics: BarChart2,
  dashboard: LayoutDashboard,
  upload_file: FileUp,
  shopping_bag: ShoppingBag,
  forum: MessageSquare,
  smart_toy: Bot,
  check_circle: CheckCircle2,
  pending_actions: Clock,
  group: Users,
  info: Info,
  arrow_back: ArrowLeft,
  chat_bubble: MessageCircle,
  ArrowRight,
  FileArchive,
  X,
  CloudUpload: UploadCloud,
  Upload: FileUp,
  XCircle,
  AlertTriangle,
  CheckCircle: CheckCircle2,
} as const;

export type IconName = keyof typeof Icons;
